name: Build Container Image
description: Build or Test a container image and apply labels
inputs:
  image-name:
    description: The full image name to build
    required: true
  docker-context:
    description: The directory context for docker build
    required: false
    default: "."
  title:
    description: The title to be used for a container image label
    required: false
    default: ""
  description:
    description: The description to be used for a container image label
    required: false
    default: ""
  authors:
    description: The authors to be used for a container image label
    required: false
    default: ""
  documentation-url:
    description: The documentation url to be used for a container image label
    required: false
    default: ""
  test-target:
    description: A test-target for testing the dockerfile
    required: false
    default: ""
  build-args:
    description: Additional build args based to docker build
    required: false
    default: ""
  secret-build-args:
    description: Additional build args based to docker build that are secret
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Build Container Image
      shell: pwsh
      run: ${{ github.action_path }}/action.ps1 
      env:
        INPUT_IMAGE_NAME: ${{ inputs.image-name }}
        INPUT_DOCKER_CONTEXT: ${{ inputs.docker-context }} 
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_DESCRIPTION: ${{ inputs.description }}
        INPUT_AUTHORS: ${{ inputs.authors }}
        INPUT_DOCUMENTATION_URL: ${{ inputs.documentation-url }}
        INPUT_TEST_TARGET: ${{ inputs.test-target }}
        INPUT_BUILD_ARGS: ${{ inputs.build-args }}
        INPUT_SECRET_BUILD_ARGS: ${{ inputs.secret-build-args }}